config/routes.rb
Rails.application.routes.draw do
  # ROOT - sets the default page when the application loads
  root "main#index"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  resources :users, except: %i[index new]

  resources :sessions, except: %i[index edit update show new destroy]

  resources :people do
    member { get :delete }
  end

  resources :addresses do
    member { get :delete }
  end

  resources :emails do
    member { get :delete }
  end

  resources :phone_numbers do
    member { get :delete }
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :person
  belongs_to :user

  validates :street, :town, :zip, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  # allows us to have access to the current user
  attribute :user
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :person
  belongs_to :user
  validates :email_address, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user
  has_many :emails
  has_many :addresses
  has_many :phone_numbers

  validates :first_name, :last_name, presence: true
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :person
  belongs_to :user
  validates :phone_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :people
  has_many :addresses
  has_many :emails
  has_many :phone_numbers
  # method that works with the password_digest column & password & password confirmation
  has_secure_password

  validates :email, format: { with: /@/, message: "Must have an @" }
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :authenticate
  def index
    @email = current_user.emails.all
  end

  def show
    @email = Email.find(params[:id])
  end

  def new
    @email = Email.new
  end

  def create
    @email = Email.new(email_params)
    @email.user = current_user
    respond_to do |format|
      if @email.save
        format.html do
          redirect_to @email, notice: "email was successfully created"
        end
        format.json { render :show, status: :created, location: @email }
      else
        format.html { render :new }
        format.json do
          render json: @email.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @email = Email.find(params[:id])
  end

  def update
    @email = Email.find(params[:id])
    respond_to do |format|
      if @email.update(email_params)
        format.html do
          redirect_to @email, notice: "email was successfully updated"
        end
        format.json { render :show, status: :created, location: @email }
      else
        format.html { render :edit }
        format.json do
          render json: @email.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def delete
    @email = Email.find(params[:id])
  end

  def destroy
    @email = Email.find(params[:id])
    @email.destroy
    respond_to do |format|
      format.html do
        redirect_to emails_url, notice: "email was successfully deleted"
      end
      format.json { head :no_content }
    end
  end

  private

  def email_params
    params.require(:email).permit(%i[person_id email_address comment])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate
  def index
    @people = current_user.people.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    @person.user = current_user
    respond_to do |format|
      if @person.save
        format.html do
          redirect_to @person, notice: "person was successfully created"
        end
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json do
          render json: @person.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    respond_to do |format|
      if @person.update(person_params)
        format.html do
          redirect_to @person, notice: "person was successfully updated"
        end
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :edit }
        format.json do
          render json: @person.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def delete
    @person = Person.find(params[:id])
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    respond_to do |format|
      format.html do
        redirect_to people_url, notice: "person was successfully deleted"
      end
      format.json { head :no_content }
    end
  end

  private

  def person_params
    params.require(:person).permit(
      %i[salutation first_name middle_name last_name ssn dob comment user_id]
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    # Only one user with this one email
    @user = User.where(email: params[:email]).first
    if @user && @user.authenticate(params[:password])
      login(@user)
      redirect_to root_path, notice: "Logged in"
    else
      redirect_to login_path, alert: "Invalid email or password."
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: %i[new create]

  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new user_params
    if @user.save
      login(@user)
      redirect_to root_path, notice: "You successfully signed up!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(%i[email password password_confirmation])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/main/index.html.erb
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <div class="container-fluid">
          <a class="navbar-brand" <%= link_to 'Address Book', root_path%>>Address Book</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" <%= link_to 'Person', people_path %>>Home</a>
              </li>
               <li class="nav-item">
                <a class="nav-link active" aria-current="page" <%= link_to 'Address', addresses_path %>>Home</a>
              </li>
               <li class="nav-item">
                <a class="nav-link active" aria-current="page" <%= link_to 'Email', emails_path %>>Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page"  <%= link_to 'Phone', phone_numbers_path %>>Home</a>
              </li>
            </ul>
            <ul class="navbar-nav mb-2 mb-md-0">
                <% if current_user %>
                    <%= link_to current_user.email, user_path(current_user) %>
                    <a class="nav-link active" aria-current="page" <%= link_to 'Logout', logout_path %>>Home</a>
                 <% else %>
                    <a class="nav-link active" aria-current="page" <%= link_to 'Login', login_path %>>Home</a>
                    <a class="nav-link active" aria-current="page" <%= link_to 'Sign Up', signup_path %>>Home</a>
                <% end %>
            </ul>
          </div>
       </div>
    </nav>

    <body>
        <div class="container-fluid">
          <h4>Must be Logged into your account to view your Address Book Details Above.</h4>
          <h6>Steps: <br />
          1. Create a Person <br />
          2. Copy Person ID from Person table <br />
          3. Add Corresponding Details to the Created Person.<br />
          4. Must use Person ID to connect the corresponding Person to their Address,Email, & Phone.</h6>
        </div>

       
    </body>

    
    
    
   
                 
   
   