config/routes.rb
Rails.application.routes.draw do
  # ROOT - sets the default page when the application loads
  root "main#index"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  resources :users, except: %i[index new]

  resources :sessions, except: %i[index edit update show new destroy]

  resources :people do
    member { get :delete }
  end

  resources :addresses do
    member { get :delete }
  end

  resources :emails do
    member { get :delete }
  end

  resources :phone_numbers do
    member { get :delete }
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :person
  belongs_to :user

  validates :street, :town, :zip, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  # allows us to have access to the current user
  attribute :user
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :person
  belongs_to :user
  validates :email_address, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user
  has_many :emails
  has_many :addresses
  has_many :phone_numbers

  validates :first_name, :last_name, presence: true
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :person
  belongs_to :user
  validates :phone_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :people
  has_many :addresses
  has_many :emails
  has_many :phone_numbers
  # method that works with the password_digest column & password & password confirmation
  has_secure_password

  validates :email, format: { with: /@/, message: "Must have an @" }
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate
  def index
    @addresses = current_user.addresses.all
  end

  def show
    @address = Address.find(params[:id])
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.user = current_user
    respond_to do |format|
      if @address.save
        format.html do
          redirect_to @address, notice: "Address was successfully created"
        end
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json do
          render json: @address.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    respond_to do |format|
      if @address.update(address_params)
        format.html do
          redirect_to @address, notice: "address was successfully updated"
        end
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :edit }
        format.json do
          render json: @address.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def delete
    @address = Address.find(params[:id])
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    respond_to do |format|
      format.html do
        redirect_to addresses_url, notice: "person was successfully deleted"
      end
      format.json { head :no_content }
    end
  end

  private

  def address_params
    params.require(:address).permit(
      :person_id,
      :street,
      :town,
      :zip,
      :state,
      :country
    )
  end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :authenticate
  def index
    @email = current_user.emails.all
  end

  def show
    @email = Email.find(params[:id])
  end

  def new
    @email = Email.new
  end

  def create
    @email = Email.new(email_params)
    @email.user = current_user
    respond_to do |format|
      if @email.save
        format.html do
          redirect_to @email, notice: "email was successfully created"
        end
        format.json { render :show, status: :created, location: @email }
      else
        format.html { render :new }
        format.json do
          render json: @email.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @email = Email.find(params[:id])
  end

  def update
    @email = Email.find(params[:id])
    respond_to do |format|
      if @email.update(email_params)
        format.html do
          redirect_to @email, notice: "email was successfully updated"
        end
        format.json { render :show, status: :created, location: @email }
      else
        format.html { render :edit }
        format.json do
          render json: @email.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def delete
    @email = Email.find(params[:id])
  end

  def destroy
    @email = Email.find(params[:id])
    @email.destroy
    respond_to do |format|
      format.html do
        redirect_to emails_url, notice: "email was successfully deleted"
      end
      format.json { head :no_content }
    end
  end

  private

  def email_params
    params.require(:email).permit(%i[person_id email_address comment])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate
  def index
    @people = current_user.people.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    @person.user = current_user
    respond_to do |format|
      if @person.save
        format.html do
          redirect_to @person, notice: "person was successfully created"
        end
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json do
          render json: @person.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    respond_to do |format|
      if @person.update(person_params)
        format.html do
          redirect_to @person, notice: "person was successfully updated"
        end
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :edit }
        format.json do
          render json: @person.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def delete
    @person = Person.find(params[:id])
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    respond_to do |format|
      format.html do
        redirect_to people_url, notice: "person was successfully deleted"
      end
      format.json { head :no_content }
    end
  end

  private

  def person_params
    params.require(:person).permit(
      %i[salutation first_name middle_name last_name ssn dob comment user_id]
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    # Only one user with this one email
    @user = User.where(email: params[:email]).first
    if @user && @user.authenticate(params[:password])
      login(@user)
      redirect_to root_path, notice: "Logged in"
    else
      redirect_to login_path, alert: "Invalid email or password."
    end
  end

  def destroy
    logout
    redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: %i[new create]

  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new user_params
    if @user.save
      login(@user)
      redirect_to root_path, notice: "You successfully signed up!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(%i[email password password_confirmation])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/people/_form.html.erb
<table class="table table-striped">
    <tr>
      <th>Salutation</th>
      <td><%= p.text_field(:salutation)%></td>
    </tr>
    <tr>
      <th>First Name</th>
      <td><%= p.text_field(:first_name)%></td>
    </tr>
    <tr>
      <th>Middle Name</th>
      <td><%= p.text_field(:middle_name)%></td>
    </tr>
    <tr>
      <th>Last Name</th>
      <td><%= p.text_field(:last_name)%></td>
    </tr>
    <tr>
      <th>SSN</th>
      <td><%= p.text_field(:ssn)%></td>
    </tr>
    <tr>
      <th>DOB</th>
      <td><%= p.date_field(:dob)%></td>
    </tr>
    <tr>
      <th>Comment</th>
      <td><%= p.text_field(:comment)%></td>
    </tr>
</table>

app/views/people/_person_row.html.erb
<tbody id="peopleTable">
    <tr id="personRow_<%= person.id %>">
                
        <th scope="row"><%= person.id%></th>
        <td><%= person.salutation %></td> 
        <td><%= person.first_name %></td>
        <td><%= person.middle_name%></td>
        <td><%= person.last_name%></td>
        <td><%= person.ssn%></td>
        <td><%= person.dob%></td>
        <td><%= person.comment%></td>
        <td>
            <%= link_to("Show", person_path(person), class: 'action show')%>
            <%= link_to("Edit", edit_person_path(person), class: 'action edit')%>
            <%= link_to("Delete", delete_person_path(person), class: 'action delete')%>
        </td>
    </tr>
</tbody>

app/views/people/backup_form.html.erb
<%= form_with(model: @person, local: false) do |form| %>
  <div class="modal-body">
    <div class="form-group">
      <%= form.label :salutation %>
      <%= form.text_field :salutation, class: 'form-control' %>
    </div>
    <div class="form-group mt-3">
      <%= form.label :first_name %>
      <%= form.text_field :first_name, class: 'form-control' %>
    </div>
    <div class="form-group mt-3">
      <%= form.label :middle_name %>
      <%= form.text_field :middle_name, class: 'form-control' %>
    </div>
    <div class="form-group mt-3">
      <%= form.label :last_name %>
      <%= form.text_field :last_name, class: 'form-control' %>
    </div>
    <div class="form-group mt-3">
      <%= form.label :ssn %>
      <%= form.text_field :ssn, class: 'form-control' %>
    </div>
    <div class="form-group mt-3">
      <%= form.label :dob %>
      <%= form.date_field :dob, class: 'form-control' %>
    </div>
    <div class="form-group mt-3">
      <%= form.label :comment %>
      <%= form.text_field :comment, class: 'form-control' %>
    </div>
  </div>
  <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= form.submit "Create Person", class: "btn btn-primary btn-md"%> 
  </div>
<% end %>


           <%= form_for(@person, remote: true) do |p| %>
        <div class="modal-body">
            <%= render(partial: 'form', locals: {p: p}) %>

        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <%= p.submit("Create Person")%>
        </div>

    <% end %>

app/views/people/create.js.erb
<% if @person.errors.any? %> 
    alert('Invalid Details');
<% else %>
    $("#peopleTable").html("<%= escape_javascript render('person_row', person: @person)%>");
<% end %>

app/views/people/delete.html.erb
<h1>Delete Page</h1>
<%= link_to('Back to Home', {controller: 'main', action: 'index'}) %><br />

<div>
    <h2>Delete Person</h2>

    <%= form_for(@person, method: 'delete') do |p| %>
        <% # url: person_path(@person). method: 'delete'%>
        <p>Are you sure you want to delete this Person permanently? </p>
        <p><%= @person.first_name %></p>

        <div class="form-buttons">
            <%= p.submit("Delete Person")%>
        </div>

    <% end %>
</div>

app/views/people/edit.html.erb
<h1>Edit Page</h1>
<%= link_to('Back to Home', {controller: 'main', action: 'index'}) %><br />

<div>
    <h2>Edit Person</h2>

    <%= form_for(@person) do |p| %>
        <% # url: person_path(@person), method: 'patch' %>
        
        <%= render(partial: 'form', locals: {p: p}) %>

        <div class="form-buttons">
            <%= p.submit("Edit Task")%>
        </div>

    <% end %>
</div>

app/views/people/index.html.erb
<h1>Index Page</h1>

<%= link_to('Back to Home', {controller: 'main', action: 'index'}) %><br />

<div>
    <h2>People</h2>
    <h4>Use: Person ID to add corresponding Emais,Addresses, & Phone Numbers</h4>

    <%= link_to("Add New Person", new_person_path, class: 'action new')%>
    
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Person ID</th>
                    <th scope="col">Salutation</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Middle Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">SSN</th>
                    <th scope="col">DOB</th>
                    <th scope="col">Comment</th>
                </tr>
            </thead>
            <% @people.each do |person| %>
            <tbody>
                <tr>
                
                <th scope="row"><%= person.id%></th>
                <td><%= person.salutation %></td>
                <td><%= person.first_name %></td>
                <td><%= person.middle_name%></td>
                <td><%= person.last_name%></td>
                <td><%= person.ssn%></td>
                <td><%= person.dob%></td>
                <td><%= person.comment%></td>
                <td>
                    <%= link_to("Show", person_path(person), class: 'action show')%>
                    <%= link_to("Edit", edit_person_path(person), class: 'action edit')%>
                    <%= link_to("Delete", delete_person_path(person), class: 'action delete')%>
                </td>
                </tr>
            </tbody>
            <% end %>
        </table>
    
</div>

app/views/people/new.html.erb
<h1>New Page</h1>
<%= link_to('Back to Home', {controller: 'main', action: 'index'}) %><br />

<div>
    <h2>Create a Person</h2>

    <%= form_for(@person) do |p| %>

        <%= render(partial: 'form', locals: {p: p}) %>

        <div>
            <%= p.submit("Create Person")%>
        </div>

    <% end %>
</div>

app/views/people/new.js.erb
$("#newUserForm").html("<%= escape_javascript render('form', person: @person)%>");

app/views/people/show.html.erb
<h1>Show Page</h1>
<%= link_to('Back to Person List', {controller: 'people', action: 'index'}) %><br />

<div>
    <h2><%= @person.first_name  %> <%= @person.last_name %></h2>

    <div>
 
    </div>

        <table class="table table-striped">
            <tr>
            <th>Salutation</th>
            <td><%= @person.salutation %></td>
            </tr>
            <tr>
            <th>First Name</th>
            <td><%= @person.first_name %></td>
            </tr>
            <tr>
            <th>Middle Name</th>
            <td><%= @person.middle_name %></td>
            </tr>
            <tr>
            <th>Last Name</th>
            <td><%= @person.last_name %></td>
            </tr>
            <tr>
            <th>SSN</th>
            <td><%= @person.ssn %></td>
            </tr>
            <tr>
            <th>DOB</th>
            <td><%= @person.dob %></td>
            </tr>
            <tr>
            <th>Comment</th>
            <td><%= @person.comment %></td>
            </tr>
        </table>

</div>

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= bootstrap_form_with(model: @user) do |f| %>
    <%= f.alert_message "Please fix errors below.", error_summary: false %>
    <%= f.email_field :email %>
    <%= f.password_field :password%>
    <%= f.password_field :password_confirmation, label: "Confirm Password"%>
    <%= f.primary 'Sign Up'%>
<% end %>

app/views/users/show.html.erb
<h2>Show </h2>
<%= link_to('Back to Home', {controller: 'main', action: 'index'}) %><br />
<p><%= @user.email %></p>