config/routes.rb
Rails.application.routes.draw do
  # ROOT - sets the default page when the application loads
  root "main#index"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  resources :users, except: %i[index new]

  resources :sessions, except: %i[index edit update show new destroy]

  resources :people do
    member { get :delete }
  end

  resources :addresses do
    member { get :delete }
  end

  resources :emails do
    member { get :delete }
  end

  resources :phone_numbers do
    member { get :delete }
  end
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :person
  belongs_to :user
  validates :phone_number, presence: true
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :authenticate
  def index
    @phone_number = current_user.phone_numbers.all
  end

  def show
    @phone_number = PhoneNumber.find(params[:id])
  end

  def new
    @phone_number = PhoneNumber.new
  end

  def create
    @phone_number = PhoneNumber.new(phone_number_params)
    @phone_number.user = current_user
    respond_to do |format|
      if @phone_number.save
        format.html do
          redirect_to @phone_number,
                      notice: "phone number was successfully created"
        end
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :new }
        format.json do
          render json: @phone_number.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @phone_number = PhoneNumber.find(params[:id])
  end

  def update
    @phone_number = PhoneNumber.find(params[:id])
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html do
          redirect_to @phone_number,
                      notice: "phone number was successfully updated"
        end
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :edit }
        format.json do
          render json: @phone_number.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def delete
    @phone_number = PhoneNumber.find(params[:id])
  end

  def destroy
    @phone_number = PhoneNumber.find(params[:id])
    @phone_number.destroy
    respond_to do |format|
      format.html do
        redirect_to phone_numbers_url,
                    notice: "phone number was successfully deleted"
      end
      format.json { head :no_content }
    end
  end

  private

  def phone_number_params
    params.require(:phone_number).permit(%i[person_id phone_number comment])
  end
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/phone_numbers/_form.html.erb
<table class="table table-striped">
  <tr>
      <th>Person ID</th>
      <td><%= p.number_field(:person_id)%></td>
    </tr>
    <tr>
      <th>Phone Number</th>
      <td><%= p.text_field(:phone_number)%></td>
    </tr>
    <tr>
      <th>Comment</th>
      <td><%= p.text_field(:comment)%></td>
    </tr>
</table>

app/views/phone_numbers/delete.html.erb
<h1>Delete Page</h1>
<%= link_to('Back to Home', {controller: 'main', action: 'index'}) %><br />

<div>
    <h2>Delete Phone Number</h2>

    <%= form_for(@phone_number, method: 'delete') do |p| %>
        <% # url: person_path(@phone_number). method: 'delete'%>
        <p>Are you sure you want to delete this phone number permanently? </p>
        <p><%= @phone_number.phone_number %></p>

        <div class="form-buttons">
            <%= p.submit("Delete phone number")%>
        </div>

    <% end %>
</div>

app/views/phone_numbers/edit.html.erb
<h1>Edit Page</h1>
<%= link_to('Back to Home', {controller: 'main', action: 'index'}) %><br />

<div>
    <h2>Edit Phone Number</h2>
    <h4>Person ID corresponds to the Person table</h4>
    <%= form_for(@phone_number) do |p| %>
        <% # url: phone_number_path(@phone_number), method: 'patch' %>
        
        <%= render(partial: 'form', locals: {p: p}) %>

        <div class="form-buttons">
            <%= p.submit("Edit Phone Number")%>
        </div>

    <% end %>
</div>

app/views/phone_numbers/index.html.erb
<h1>Index Page</h1>

<%= link_to('Back to Home', {controller: 'main', action: 'index'}) %><br />

<div>
    <h2>Phone Numbers</h2>

    <%= link_to("Add New Phone Number", new_phone_number_path, class: 'action new')%>
    
        <table class="table table-striped">
            <thead>
                <tr>
                    
                    <th scope="col">Phone Number</th>
                    <th scope="col">Comment</th>
                </tr>
            </thead>
            <% @phone_number.each do |phone_number| %>
            <tbody>
                <tr>
                
                <td><%= phone_number.phone_number %></td>
                <td><%= phone_number.comment%></td>
                <td>
                    <%= link_to("Show", phone_number_path(phone_number), class: 'action show')%>
                    <%= link_to("Edit", edit_phone_number_path(phone_number), class: 'action edit')%>
                    <%= link_to("Delete", delete_phone_number_path(phone_number), class: 'action delete')%>
                </td>
                </tr>
            </tbody>
            <% end %>
        </table>
    
</div>

app/views/phone_numbers/new.html.erb
<h1>New Page</h1>
<%= link_to('Back to Home', {controller: 'main', action: 'index'}) %><br />

<div>
    <h2>Create a Phone Number</h2>
    <h4>Person ID corresponds to the Person table</h4>
    <%= form_for(@phone_number) do |p| %>

        <%= render(partial: 'form', locals: {p: p}) %>

        <div>
            <%= p.submit("Create Phone Number")%>
        </div>

    <% end %>
</div>

app/views/phone_numbers/show.html.erb
<h1>Show Page</h1>
<%= link_to('Back to Phone Number List', {controller: 'phone_numbers', action: 'index'}) %><br />

<div>
    <h2>Phone Details</h2>
    <h4>Person ID corresponds to the Person table</h4>
    <div>
 
    </div>

        <table class="table table-striped">
            <tr>
            <th>Person ID</th>
            <td><%= @phone_number.person_id %></td>
            </tr>
            <tr>
            <th>Phone Number</th>
            <td><%= @phone_number.phone_number %></td>
            </tr>
            <tr>
            <th>Comment</th>
            <td><%= @phone_number.comment %></td>
            </tr>
        </table>

</div>