config/routes.rb
Rails.application.routes.draw do
  # ROOT - sets the default page when the application loads
  root "main#index"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

  resources :users, except: %i[index new]

  resources :sessions, except: %i[index edit update show new destroy]

  resources :people do
    member { get :delete }
  end

  resources :addresses do
    member { get :delete }
  end

  resources :emails do
    member { get :delete }
  end

  resources :phone_numbers do
    member { get :delete }
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :person
  belongs_to :user

  validates :street, :town, :zip, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  # allows us to have access to the current user
  attribute :user
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :person
  belongs_to :user
  validates :email_address, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :user
  has_many :emails
  has_many :addresses
  has_many :phone_numbers

  validates :first_name, :last_name, presence: true
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :person
  belongs_to :user
  validates :phone_number, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :people
  has_many :addresses
  has_many :emails
  has_many :phone_numbers
  # method that works with the password_digest column & password & password confirmation
  has_secure_password

  validates :email, format: { with: /@/, message: "Must have an @" }
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :authenticate
  def index
    @addresses = current_user.addresses.all
  end

  def show
    @address = Address.find(params[:id])
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.user = current_user
    respond_to do |format|
      if @address.save
        format.html do
          redirect_to @address, notice: "Address was successfully created"
        end
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json do
          render json: @address.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    respond_to do |format|
      if @address.update(address_params)
        format.html do
          redirect_to @address, notice: "address was successfully updated"
        end
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :edit }
        format.json do
          render json: @address.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def delete
    @address = Address.find(params[:id])
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    respond_to do |format|
      format.html do
        redirect_to addresses_url, notice: "person was successfully deleted"
      end
      format.json { head :no_content }
    end
  end

  private

  def address_params
    params.require(:address).permit(
      :person_id,
      :street,
      :town,
      :zip,
      :state,
      :country
    )
  end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :authenticate
  def index
    @email = current_user.emails.all
  end

  def show
    @email = Email.find(params[:id])
  end

  def new
    @email = Email.new
  end

  def create
    @email = Email.new(email_params)
    @email.user = current_user
    respond_to do |format|
      if @email.save
        format.html do
          redirect_to @email, notice: "email was successfully created"
        end
        format.json { render :show, status: :created, location: @email }
      else
        format.html { render :new }
        format.json do
          render json: @email.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @email = Email.find(params[:id])
  end

  def update
    @email = Email.find(params[:id])
    respond_to do |format|
      if @email.update(email_params)
        format.html do
          redirect_to @email, notice: "email was successfully updated"
        end
        format.json { render :show, status: :created, location: @email }
      else
        format.html { render :edit }
        format.json do
          render json: @email.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def delete
    @email = Email.find(params[:id])
  end

  def destroy
    @email = Email.find(params[:id])
    @email.destroy
    respond_to do |format|
      format.html do
        redirect_to emails_url, notice: "email was successfully deleted"
      end
      format.json { head :no_content }
    end
  end

  private

  def email_params
    params.require(:email).permit(%i[person_id email_address comment])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate
  def index
    @people = current_user.people.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)
    @person.user = current_user
    respond_to do |format|
      if @person.save
        format.html do
          redirect_to @person, notice: "person was successfully created"
        end
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json do
          render json: @person.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    respond_to do |format|
      if @person.update(person_params)
        format.html do
          redirect_to @person, notice: "person was successfully updated"
        end
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :edit }
        format.json do
          render json: @person.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def delete
    @person = Person.find(params[:id])
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    respond_to do |format|
      format.html do
        redirect_to people_url, notice: "person was successfully deleted"
      end
      format.json { head :no_content }
    end
  end

  private

  def person_params
    params.require(:person).permit(
      %i[salutation first_name middle_name last_name ssn dob comment user_id]
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate, except: %i[new create]

  def show
    @user = User.find(params[:id])
  end
  def new
    @user = User.new
  end
  def create
    @user = User.new user_params
    if @user.save
      login(@user)
      redirect_to root_path, notice: "You successfully signed up!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(%i[email password password_confirmation])
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_form.html.erb
<table class="table table-striped">
    <tr>
      <th>Person ID</th>
      <td><%= a.number_field(:person_id)%></td>
    </tr>
    <tr>
      <th>Street</th>
      <td><%= a.text_field(:street)%></td>
    </tr>
    <tr>
      <th>Town</th>
      <td><%= a.text_field(:town)%></td>
    </tr>
    <tr>
      <th>Zip</th>
      <td><%= a.number_field(:zip)%></td>
    </tr>
    <tr>
      <th>State</th>
      <td><%= a.text_field(:state)%></td>
    </tr>
    <tr>
      <th>Country</th>
      <td><%= a.text_field(:country)%></td>
    </tr>
</table>

app/views/addresses/delete.html.erb
<h1>Delete Page</h1>
<%= link_to('Back to Address List', {controller: 'addresses', action: 'index'}) %><br />

<div>
    <h2>Delete Address</h2>

    <%= form_for(@address, method: 'delete') do |a| %>
        <% # url: address_path(@address). method: 'delete'%>
        <p>Are you sure you want to delete this Address permanently? </p>
        <p><%= @address.street %></p>
        <div class="form-buttons">
            <%= a.submit("Delete Address")%>
        </div>
    <% end %>
</div>

app/views/addresses/edit.html.erb
<h1>Edit Page</h1>
<%= link_to('Back to Address List', {controller: 'addresses', action: 'index'}) %><br />

<div>
    <h2>Edit Address</h2>
    <h4>Person ID corresponds to the Person table</h4>
    <%= form_for(@address) do |a| %>
        <%= render(partial: 'form', locals: {a: a}) %>

        <div class="form-buttons">
            <%= a.submit("Edit Address")%>
        </div>

    <% end %>
</div>

app/views/addresses/index.html.erb
<h1>Index Page</h1>

<%= link_to('Back to Home', {controller: 'main', action: 'index'}) %><br />

<div>
    <h2>Address</h2>

    <%= link_to("Add New Address", new_address_path, class: 'action new')%>
    
        <table class="table table-striped">
            <thead>
                <tr>
                    
                    <th scope="col">Street</th>
                    <th scope="col">Town</th>
                    <th scope="col">State</th>
                    <th scope="col">Zip</th>
                    <th scope="col">Country</th>
                </tr>
            </thead>
            <% @addresses.each do |address| %>
            <tbody>
                <tr>
               
                <td><%= address.street %></td>
                <td><%= address.town%></td>
                <td><%= address.state%></td>
                <td><%= address.zip%></td>
                <td><%= address.country%></td>
                <td>
                    <%= link_to("Show", address_path(address), class: 'action show')%>
                    <%= link_to("Edit", edit_address_path(address), class: 'action edit')%>
                    <%= link_to("Delete", delete_address_path(address), class: 'action delete')%>
                </td>
                </tr>
            </tbody>
            <% end %>
        </table>
    
</div>

app/views/addresses/new.html.erb
<h1>New Page</h1>
<%= link_to('Back to Home', {controller: 'main', action: 'index'}) %><br />

<div>
    <h2>Create a Address</h2>
    <h4>Person ID corresponds to the Person table</h4>

    <%= form_for(@address) do |a| %>
        <%= render(partial: 'form', locals: {a: a}) %>

        <div>
            <%= a.submit("Create Address")%>
        </div>

    <% end %>
</div>

app/views/addresses/show.html.erb
<h1>Show Page</h1>
<%= link_to('Back to Address List', {controller: 'addresses', action: 'index'}) %><br />

<div>
    <h2>Address Info.</h2>
    <h4>Person ID corresponds to the Person table</h4>
    <div>
 
    </div>

        <table class="table table-striped">
            <tr>
            <th>Person ID</th>
            <td><%= @address.person_id %></td>
            </tr>
            <tr>
            <th>Street</th>
            <td><%= @address.street %></td>
            </tr>
            <tr>
            <th>Town</th>
            <td><%= @address.town %></td>
            </tr>
            <tr>
            <th>State</th>
            <td><%= @address.state %></td>
            </tr>
            <tr>
            <th>Zip</th>
            <td><%= @address.zip %></td>
            </tr>
            <tr>
            <th>Country</th>
            <td><%= @address.country %></td>
            </tr>
            <tr>
        </table>

</div>